import inspect
import multiprocessing
import os
import subprocess
import threading
import time
from typing import List

import gpiozero
from numpy import insert

import controlledEnd
import frameDecorator
from components import lcd20
from utils import configLoader, exceptionRecorder, Logger, LogMsg

__filename=os.path.basename(os.path.abspath(__file__))


class UniversalControl:
    '''
    UniversalControl is a central controller class that manages multiple controlled ends (widgets)
    and routes hardware input events (such as button presses and rotary encoder actions) to the
    currently active controlled end. It also handles inter-widget messaging, LCD display updates,
    and GPIO initialization for hardware controls.
    Attributes:
        __controlledEndList (List[controlledEnd.ControlledEnd]): List of controlled end instances.
        __config (ConfigLoader): Configuration loader for hardware pin and debug settings.
        __logger (Logger): Logger instance for debugging and info messages.
        __enable (bool): Flag indicating if input handling is enabled.
        __rights (int): Index of the currently active controlled end.
        __lastWidget (str): ID of the last controlled end, used for return operations.
        __lcd (lcd20.Lcd): LCD display instance.
        __frame (Any): Current frame generated by the active controlled end.
        __signal (bool): Signal flag for switching controlled ends.
        __w (frameDecorator.Warining): Warning frame decorator instance.
        __frameList (multiprocessing.Queue): Queue for passing frames to the display process.
        __t (multiprocessing.Process): Process for displaying images on the LCD.
    Methods:
        __init__(lcd, controlledEndList):
            Initializes UniversalControl, sets up hardware, logging, and controlled ends.
        __gpioInit():
            Initializes GPIO input devices and assigns event handlers for hardware controls.
        __msgReceiver(msg):
            Handles messages sent to UniversalControl, such as system commands.
        __irq(_id):
            Switches control to the controlled end with the specified ID.
        __msgSender(sender, receiver, msg):
            Routes messages between controlled ends or to UniversalControl.
        showImageInAnotherThread(imgList):
            Continuously displays images from a list in a separate thread.
        showImageInAnotherProcess(imgList):
            Continuously displays images from a multiprocessing queue in a separate process.
        __centerPressAction(), __centerReleaseAction(), __circlePressAction(), __squarePressAction(),
        __crossPressAction(), __shutterPressAction(), __upPressAction(), __downPressAction(),
        __rightPressAction(), __leftPressAction(), __upReleaseAction(), __downReleaseAction(),
        __rightReleaseAction(), __leftReleaseAction(), __rotaryEncoderSelectAction(),
        __rotaryEncoderClockwise(), __rotaryEncoderCounterClockwise():
            Event handlers for various hardware input actions, routed to the active controlled end.
        mainLoop():
            Main event loop that manages the lifecycle of controlled ends, handles switching,
            and updates the LCD display with frames from the active controlled end.
    '''

    def __init__(self, lcd: lcd20.Lcd, controlledEnd_list: List[controlledEnd.ControlledEnd]):
        self.__controlledEnd_list = controlledEnd_list
        self.__config = configLoader.ConfigLoader('./config.json')
        self.__logger = Logger()
        # console_level=
        # self.__config['debug_level']
        # )
        self.__enable = True
        self.__rights = 0  # Current controlled end in use
        self.__last_widget = None  # Last controlled end, used for return operation
        self.__lcd = lcd
        self.__lcd.init()
        self.__frame = None  # Frame gen by current controlled end
        self.__signal = False

        for i in self.__controlledEnd_list:
            i.irq(self.__irq)
            # Assign UniversalControl.__msgSender to controlledEnd
            i.msg_sender(self.__msg_sender)

        self.__gpio_init()

        self.__w = frameDecorator.Warining()
        self.__frame_list = multiprocessing.Queue(maxsize=1)
        self.__t = multiprocessing.Process(
            target=self.show_image_in_another_process, args=(self.__frame_list,))
        self.__logger.info(
            LogMsg(
                content='UniversalControl initialized',
                module=self.__module__,
                filename=os.path.basename(os.path.abspath(__file__)),
                currentframe=inspect.currentframe()
            )
        )

    def __gpio_init(self):
        self.__shutter = gpiozero.DigitalInputDevice(
            pin=self.__config['pin']['shutter']
        )
        self.__shutter.when_activated = self.__shutter_press_action

        self.__square = gpiozero.DigitalInputDevice(
            pin=self.__config['pin']['square']
        )
        self.__square.when_activated = self.__square_press_action

        self.__cross = gpiozero.DigitalInputDevice(
            pin=self.__config['pin']['cross']
        )
        self.__cross.when_activated = self.__cross_press_action

        self.__circle = gpiozero.DigitalInputDevice(
            pin=self.__config['pin']['circle']
        )
        self.__circle.when_activated = self.__circle_press_action

        self.__up = gpiozero.DigitalInputDevice(
            pin=self.__config['pin']['up']
        )
        self.__up.when_activated = self.__up_press_action
        self.__up.when_deactivated = self.__up_release_action

        self.__down = gpiozero.DigitalInputDevice(
            pin=self.__config['pin']['down']
        )
        self.__down.when_activated = self.__down_press_action
        self.__down.when_deactivated = self.__down_release_action

        self.__left = gpiozero.DigitalInputDevice(
            pin=self.__config['pin']['left']
        )
        self.__left.when_activated = self.__left_press_action
        self.__left.when_deactivated = self.__left_release_action

        self.__right = gpiozero.DigitalInputDevice(
            pin=self.__config['pin']['right']
        )
        self.__right.when_activated = self.__right_press_action
        self.__right.when_deactivated = self.__right_release_action

        self.__center = gpiozero.DigitalInputDevice(
            pin=self.__config['pin']['center']
        )
        self.__center.when_activated = self.__center_press_action
        self.__center.when_deactivated = self.__center_release_action

        self.__rotaryEncoderSelect = gpiozero.DigitalInputDevice(
            pin=self.__config['pin']['rotaryEncoder1S']
        )
        self.__rotaryEncoderSelect.when_activated = self.__rotary_encoder_select_action

        self.__rotaryEncoder = gpiozero.RotaryEncoder(
            self.__config['pin']['rotaryEncoder1A'],
            self.__config['pin']['rotaryEncoder1B']
        )
        self.__rotaryEncoder.when_rotated_clockwise = self.__rotary_encoder_clockwise
        self.__rotaryEncoder.when_rotated_counter_clockwise = self.__rotary_encoder_counter_clockwise

    def __msg_receiver(self, msg):
        if msg == 'restart':
            subprocess.run(['sudo', 'reboot'])

    @exceptionRecorder()
    def __irq(self, _id: str):
        """
        Switch the control right of controlledEnd.
        """
        self.__logger.info(
            LogMsg(
                content="Irq to {}".format(_id),
                module=self.__module__,
                filename=os.path.basename(os.path.abspath(__file__)),
                currentframe=inspect.currentframe()
            )
        )
        # Look up controlled end in list
        for index, widget in enumerate(self.__controlledEnd_list):
            if widget.id == _id:
                self.__signal = True
                self.__last_widget = self.__controlledEnd_list[self.__rights].id
                oldRights = self.__rights
                self.__rights = index
                self.__controlledEnd_list[oldRights].on_exit()
                break
        else:
            raise LookupError(_id)

    @exceptionRecorder()
    def __msg_sender(self, sender: str, receiver: str, msg):
        self.__logger.info(
            LogMsg(
                content='Message from {} to {}'.format(sender, receiver),
                module=self.__module__,
                filename=os.path.basename(os.path.abspath(__file__)),
                currentframe=inspect.currentframe()
            )

        )
        if receiver == 'UniversalControl':
            self.__msg_receiver(msg)
            return
        for widget in self.__controlledEnd_list:
            if widget.id == receiver:
                widget.msg_receiver(sender, msg)
                break
        else:
            raise LookupError(receiver)

    @exceptionRecorder()
    def show_image_in_another_process(self, imgList: multiprocessing.Queue):
        while True:
            self.__lcd.show_image(imgList.get(True))

    @exceptionRecorder()
    def __center_press_action(self):
        self.__logger.debug(
            LogMsg(
                content='Center pressed',
                module=self.__module__,
                filename=os.path.basename(os.path.abspath(__file__)),
                currentframe=inspect.currentframe()
            )
        )
        if not self.__enable:
            return
        self.__controlledEnd_list[self.__rights].center_press_action()

    @exceptionRecorder()
    def __center_release_action(self):
        self.__logger.debug(
            LogMsg(
                content='Center relesed',
                module=self.__module__,
                filename=os.path.basename(os.path.abspath(__file__)),
                currentframe=inspect.currentframe()
            )
        )
        if not self.__enable:
            return

        self.__controlledEnd_list[self.__rights].center_release_action()

    def __circle_press_action(self):
        self.__logger.debug(
            LogMsg(
                content='circle pressed',
                module=self.__module__,
                filename=os.path.basename(os.path.abspath(__file__)),
                currentframe=inspect.currentframe()
            )
        )
        if not self.__enable:
            return
        self.__controlledEnd_list[self.__rights].circle_press_action()

    @exceptionRecorder()
    def __square_press_action(self):
        self.__logger.debug(
            LogMsg(
                content='Square pressed',
                module=self.__module__,
                filename=os.path.basename(os.path.abspath(__file__)),
                currentframe=inspect.currentframe()
            )
        )
        if not self.__enable:
            return

        self.__controlledEnd_list[self.__rights].square_press_action()

    @exceptionRecorder()
    def __cross_press_action(self):
        self.__logger.debug(
            LogMsg(
                content='Cross pressed',
                module=self.__module__,
                filename=os.path.basename(os.path.abspath(__file__)),
                currentframe=inspect.currentframe()
            )
        )
        if not self.__enable:
            return

        self.__controlledEnd_list[self.__rights].cross_press_action()

    def __shutter_press_action(self):
        self.__logger.debug(
            LogMsg(
                content='Shutter pressed',
                module=self.__module__,
                filename=os.path.basename(os.path.abspath(__file__)),
                currentframe=inspect.currentframe()
            )
        )
        if not self.__enable:
            return

        self.__controlledEnd_list[self.__rights].shutter_press_action()

    def __up_press_action(self):
        self.__logger.debug(
            LogMsg(
                content='Up pressed',
                module=self.__module__,
                filename=os.path.basename(os.path.abspath(__file__)),
                currentframe=inspect.currentframe()
            )
        )
        self.__controlledEnd_list[self.__rights].up_press_action()

    def __down_press_action(self):
        self.__logger.debug(
            LogMsg(
                content='Down pressed',
                module=self.__module__,
                filename=os.path.basename(os.path.abspath(__file__)),
                currentframe=inspect.currentframe()
            )
        )

        self.__controlledEnd_list[self.__rights].down_press_action()

    def __right_press_action(self):
        self.__logger.debug(
            LogMsg(
                content='Right pressed',
                module=self.__module__,
                filename=os.path.basename(os.path.abspath(__file__)),
                currentframe=inspect.currentframe()
            )
        )

        self.__controlledEnd_list[self.__rights].right_press_action()

    def __left_press_action(self):
        self.__logger.debug(
            LogMsg(
                content='Left pressed',
                module=self.__module__,
                filename=os.path.basename(os.path.abspath(__file__)),
                currentframe=inspect.currentframe()
            )
        )

        self.__controlledEnd_list[self.__rights].left_press_action()

    def __up_release_action(self):
        self.__logger.debug(
            LogMsg(
                content='Up released',
                module=self.__module__,
                filename=os.path.basename(os.path.abspath(__file__)),
                currentframe=inspect.currentframe()
            )
        )
        self.__controlledEnd_list[self.__rights].up_release_action()

    def __down_release_action(self):
        self.__logger.debug(
            LogMsg(
                content='Down released',
                module=self.__module__,
                filename=os.path.basename(os.path.abspath(__file__)),
                currentframe=inspect.currentframe()
            )
        )
        self.__controlledEnd_list[self.__rights].down_release_action()

    def __right_release_action(self):
        self.__logger.debug(
            LogMsg(
                content='Right released',
                module=self.__module__,
                filename=os.path.basename(os.path.abspath(__file__)),
                currentframe=inspect.currentframe()
            )
        )
        self.__controlledEnd_list[self.__rights].right_release_action()

    def __left_release_action(self):
        self.__logger.debug(
            LogMsg(
                content='Left released',
                module=self.__module__,
                filename=os.path.basename(os.path.abspath(__file__)),
                currentframe=inspect.currentframe()
            )
        )
        self.__controlledEnd_list[self.__rights].left_release_action()

    def __rotary_encoder_select_action(self):
        self.__logger.debug(
            LogMsg(
                content='Rotary encoder selected',
                module=self.__module__,
                filename=os.path.basename(os.path.abspath(__file__)),
                currentframe=inspect.currentframe()
            )
        )
        if not self.__enable:
            return
        self.__controlledEnd_list[self.__rights].rotary_encoder_select()

    def __rotary_encoder_clockwise(self):
        self.__logger.debug(
            LogMsg(
                content='Rotary encoder clockwise',
                module=self.__module__,
                filename=os.path.basename(os.path.abspath(__file__)),
                currentframe=inspect.currentframe()
            )
        )
        if not self.__enable:
            return
        self.__controlledEnd_list[self.__rights].rotary_encoder_clockwise()

    def __rotary_encoder_counter_clockwise(self):
        self.__logger.debug(
            LogMsg(
                content='Rotary encoder counter clockwise',
                module=self.__module__,
                filename=os.path.basename(os.path.abspath(__file__)),
                currentframe=inspect.currentframe()
            )
        )
        if not self.__enable:
            return
        self.__controlledEnd_list[self.__rights].rotary_encoder_counter_clockwise()

    @exceptionRecorder()
    def mainLoop(self):
        self.__t.start()
        self.__logger.info(
            LogMsg(
                content='Enter mainloop',
                module=self.__module__,
                filename=os.path.basename(os.path.abspath(__file__)),
                currentframe=inspect.currentframe()
            )
        )
        try:
            while True:
                self.__controlledEnd_list[self.__rights].on_enter(
                    self.__last_widget
                )

                for self.__frame in self.__controlledEnd_list[self.__rights].main_loop():
                    if self.__signal:
                        self.__signal = False
                        break
                    while not self.__enable:
                        time.sleep(0.1)
                    self.__frame_list.put(self.__frame, True)
        except KeyboardInterrupt:
            self.__logger.info(
                LogMsg(
                    content='UniversalControl stopped',
                    module=self.__module__,
                    filename=os.path.basename(os.path.abspath(__file__)),
                    currentframe=inspect.currentframe()
                )
            )
            self.__t.terminate()
            self.__lcd.backlight(False)
            exit(0)
